import type { Metadata } from "next";
import { Kumbh_Sans, Roboto } from "next/font/google";
import "./globals.css";
// import Navbar from "@/components/shared/navbar";
// import Footer from "@/components/shared/Footer";

const kumbhSans = Kumbh_Sans({
  subsets: ["latin"],
  weight: ["400", "700"], // Adjust as needed
  variable: "--font-kumbh-sans", // Custom CSS variable
});

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"], // You can add more weights
  variable: "--font-roboto", // Custom CSS variable
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${kumbhSans.variable} ${roboto.variable} bg-[--primaryWhite] antialiased grid grid-rows-[1fr_auto] min-h-screen box-border`}
      >
        {/* <Navbar />
        <div
          style={{ background: "url(/images/BGExport.png) no-repeat" }}
          className="bg-cover bg-top py-10"
        > */}
        {children}
        {/* </div>
        <Footer /> */}
      </body>
    </html>
  );
}
